### ISSUE TITLE
Zotero not able to parse unicode characters at some places

### ISSUE THREAD

**Issue by gkumbhat** [diging/tethne#81] opened 2015-09-14 00:05 UTC
When we try to run the test cases on some data, it sometimes fails if the data has unicode characters at some places (example: title)

The problem occurred while running the test file, using following command:
`nosetests tethne/tests/test_readers_zotero.py`

Expected output:
`OK`

ERROR: test_read_nocorpus (tethne.tests.test_readers_zotero.TestZoteroParser)

```
Traceback (most recent call last):
  File "/home/gkumbhat/tethne/tethne/tethne/tests/test_readers_zotero.py", line 25, in test_read_nocorpus
    papers = read(datapath, corpus=False)
  File "/home/gkumbhat/tethne/tethne/tethne/readers/zotero.py", line 177, in read
    papers = ZoteroParser(path).parse()
  File "/home/gkumbhat/tethne/tethne/tethne/readers/base.py", line 278, in parse
    self.handle(tag, o)
  File "/home/gkumbhat/tethne/tethne/tethne/readers/base.py", line 287, in handle
    data = handler(data)
  File "/home/gkumbhat/tethne/tethne/tethne/readers/zotero.py", line 64, in handle_abstract
    return str(value)
  File "/home/gkumbhat/.virtualenvs/tethneEnv/lib/python2.7/site-packages/rdflib/term.py", line 1262, in __str__
    return self.encode()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 116: ordinal not in range(128)

```

**Comment by nischalsamji** [comment] 2015-09-15 21:45
Issue also present in tethne/readers/zotero.py in handle_author() function.

**Comment by nischalsamji** [comment] 2015-10-02 01:39
Guess this is a duplicate of issue  - #85

**Closed as completed by nischalsamji** 2015-10-02 01:39 UTC
Labels: bug
