### ISSUE TITLE
When trying to install via pip "No distributions matching the version for tethne"

### ISSUE THREAD

**Issue by kaiello** [diging/tethne#36] opened 2014-08-19 04:32 UTC
Downloaded and unzipped tethne 0.6.2-beta, when running install from command line using pip unable to install

'''
Downloading/unpacking tethne
  Could not find a version that satisfies the requirement tethne (from versions: 0.3.0-alpha, 0.3.1-alpha, 0.4.0-alpha, 0.4.2-alpha, 0.6.0-beta, 0.6.1-beta, 0.6.2-beta)
Cleaning up...
No distributions matching the version for tethne
Storing debug log for failure in /Users/Kenneth/.pip/pip.log
'''

![screen shot 2014-08-18 at 9 34 18 pm](https://cloud.githubusercontent.com/assets/8186095/3961704/1fee612e-275a-11e4-8b26-49580ec39f78.png)

**Comment by kaiello** [comment] 2014-08-19 05:10
Was able to install using --pre

**Comment by erickpeirson** [comment] 2014-08-19 13:59
This is a duplicate of #24, closing.

**Closed as completed** 2014-08-19 13:59 UTC
Labels: duplicate, wontfix
